apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: harmony-shared-external
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: metrics-server
            wave: "-4"
            repoURL: https://kubernetes-sigs.github.io/metrics-server/
            chart: metrics-server
            targetRevision: 3.12.1
            namespace: kube-system

          - name: kube-prometheus-stack
            wave: "-4"
            repoURL: https://prometheus-community.github.io/helm-charts
            chart: kube-prometheus-stack
            targetRevision: 61.3.1
            namespace: monitoring

          - name: automq
            wave: "-1"
            repoURL: registry-1.docker.io/bitnamicharts
            chart: kafka
            targetRevision: 31.5.0
            namespace: harmony

          - name: centrifugo
            wave: "0"
            repoURL: https://centrifugal.github.io/helm-charts
            chart: centrifugo
            targetRevision: 2.0.3
            namespace: harmony

          - name: redpanda-connect
            wave: "0"
            repoURL: https://charts.redpanda.com
            chart: connect
            targetRevision: 3.1.0
            namespace: harmony

          - name: kafbat-ui
            wave: "0"
            repoURL: https://kafbat.github.io/helm-charts
            chart: kafka-ui
            targetRevision: 0.9.1
            namespace: harmony

  template:
    metadata:
      name: "local-{{ .name }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/notDroid/HarmonyChat.git
          targetRevision: HEAD
          ref: values

        - repoURL: "{{ .repoURL }}"
          chart: "{{ .chart }}"
          targetRevision: "{{ .targetRevision }}"
          helm:
            releaseName: "{{ .name }}"
            valueFiles:
              - $values/infra/environments/local/rendered-values/local/{{ .name }}.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
