name: Release Manifests

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        env: [local, staging]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install go-task
        uses: go-task/setup-task@v2
        with:
          version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Install Helm
        uses: azure/setup-helm@v5.0.0

      - name: Install Helmfile
        uses: mamezou-tech/setup-helmfile@v2.2.0

      - name: Setup ORAS
        uses: oras-project/setup-oras@v2.0.0
        with:
          version: 1.2.0

      - name: Extract Version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish Manifests for ${{ matrix.env }}
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          task infra:publish K8S_ENV=${{ matrix.env }} CHART_VERSION=$VERSION REGISTRY_BASE="ghcr.io/$REPO_OWNER"