name: Release Manifests

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        env: [staging]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Setup ORAS
        uses: oras-project/setup-oras@v4
        with:
          version: 1.2.0

      - name: Extract Version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish Manifests for ${{ matrix.env }}
        run: |
          devbox run -- task publish K8S_ENV=${{ matrix.env }} ARTIFACT_VERSION=$VERSION REGISTRY_URL="ghcr.io/${{ github.repository_owner }}"
